### ISSUE TITLE
Error when running the VTOL

### ISSUE THREAD

**Issue by jjxx2** [suavecode/Tutorials#33]
Optimum motor design failed. Using slack constraints
Traceback (most recent call last):
  File "c:\Users\soren\Downloads\tut_eVTOL.py", line 592, in <module>
    main()
  File "c:\Users\soren\Downloads\tut_eVTOL.py", line 48, in main
    results = mission.evaluate()
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\suave-2.5.2-py3.11.egg\SUAVE\Analyses\Mission\Segments\Segment.py", line 180, in evaluate
    self.process(self)
  File "C:\Users\soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\suave-2.5.2-py3.11.egg\SUAVE\Analyses\Process.py", line 96, in __call__
    return self.evaluate(*args,**kwarg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\suave-2.5.2-py3.11.egg\SUAVE\Analyses\Process.py", line 67, in evaluate
    result = step(*args,**kwarg)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\suave-2.5.2-py3.11.egg\SUAVE\Methods\Missions\Segments\Common\Sub_Segments.py", line 137, in sequential_sub_segments
    sub_segment.evaluate()
  File "C:\Users\soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\suave-2.5.2-py3.11.egg\SUAVE\Analyses\Mission\Segments\Segment.py", line 180, in evaluate
    self.process(self)
  File "C:\Users\soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\suave-2.5.2-py3.11.egg\SUAVE\Analyses\Process.py", line 96, in __call__
    return self.evaluate(*args,**kwarg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\suave-2.5.2-py3.11.egg\SUAVE\Analyses\Process.py", line 65, in evaluate
    result = step.evaluate(*args,**kwarg)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\suave-2.5.2-py3.11.egg\SUAVE\Analyses\Process.py", line 67, in evaluate
    result = step(*args,**kwarg)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\suave-2.5.2-py3.11.egg\SUAVE\Methods\Missions\Segments\converge_root.py", line 50, in converge_root
    unknowns,infodict,ier,msg = root_finder( iterate,
                                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\optimize\_minpack_py.py", line 166, in fsolve
    res = _root_hybr(func, x0, args, jac=fprime, **options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\optimize\_minpack_py.py", line 232, in _root_hybr
    shape, dtype = _check_func('fsolve', 'func', func, x0, args, n, (n,))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\optimize\_minpack_py.py", line 29, in _check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],) + args)))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\suave-2.5.2-py3.11.egg\SUAVE\Methods\Missions\Segments\converge_root.py", line 99, in iterate
    segment.process.iterate(segment)
  File "C:\Users\soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\suave-2.5.2-py3.11.egg\SUAVE\Analyses\Process.py", line 96, in __call__
    return self.evaluate(*args,**kwarg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\suave-2.5.2-py3.11.egg\SUAVE\Analyses\Process.py", line 65, in evaluate
    result = step.evaluate(*args,**kwarg)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\suave-2.5.2-py3.11.egg\SUAVE\Analyses\Process.py", line 67, in evaluate
    result = step(*args,**kwarg)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\suave-2.5.2-py3.11.egg\SUAVE\Methods\Missions\Segments\Common\Energy.py", line 87, in update_thrust
    results   = energy_model.evaluate_thrust(segment.state)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\suave-2.5.2-py3.11.egg\SUAVE\Analyses\Energy\Energy.py", line 65, in evaluate_thrust
    results = network.evaluate_thrust(state)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\suave-2.5.2-py3.11.egg\SUAVE\Components\Energy\Networks\Network.py", line 143, in evaluate_thrust
    results_p = net.evaluate_thrust(state)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\suave-2.5.2-py3.11.egg\SUAVE\Components\Energy\Networks\Lift_Cruise.py", line 167, in evaluate_thrust
    volts = battery.compute_voltage(state)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\suave-2.5.2-py3.11.egg\SUAVE\Components\Energy\Storages\Batteries\Constant_Mass\Lithium_Ion_LiNiMnCoO2_18650.py", line 432, in compute_voltage
    V_ul_cell = compute_NMC_cell_state_variables(battery_data,SOC,T_cell,I_cell)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soren\AppData\Local\Programs\Python\Python311\Lib\site-packages\suave-2.5.2-py3.11.egg\SUAVE\Methods\Power\Battery\Cell_Cycle_Models\LiNiMnCoO2_cell_cycle_model.py", line 51, in compute_NMC_cell_state_variables
    V_ul           = np.atleast_2d(battery_data.Voltage(pts)[:,1]).T
                                   ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'Voltage'

**Comment by wgl1999** [comment]
Hi, I also meet this problem, do you know how to figure it out?
